name: Build Site
on:
  push:
    branches:
      - dev
jobs:
  Build_Site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3
      - name: Create folder
        run: |
          mkdir -p docs
          cp -r Dungeon/ docs/ && cp -r Resource/ docs/ && cp -r Staircase/ docs/ && cp README.md docs/
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Build indexs
        run: |
          pip install natsort
          python scripts/build_site.py
      - name: Build MkDocs
        run: |
          pip install mkdocs
          mkdocs gh-deploy --force --clean --verbose
