name: Build Site
on:
  push:
    branches:
      - dev
jobs:
  Build_Site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Build indexes
        run: |
          python scripts/build_site.py
      - name: Copy Content
        run: |
          mkdir -p docs
          cp -r Dungeon/ docs/
          cp README.md docs/
      - name: Build MkDocs
        run: |
          pip install mkdocs
          mkdocs gh-deploy --force --clean --verbose
