name: Build Site
on:
  push:
    branches:
      - dev
jobs:
  make_dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create folder
        run: |
          mkdir -p docs
          cp -r Dungeon/ docs/ && cp -r Resource/ docs/ && cp -r Staircase/ docs/ && cp README.md docs/
      - name: Build MkDocs
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        run: |
          pip install mkdocs
          mkdocs gh-deploy --force --clean --verbose
